name: Functional tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13", "3.14", "3.15"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        chmod 755 ./wtr
    - name: Test commands
      run: |
        WTR_CACHE=./wtr.db ./wtr list -c locations
        WTR_CACHE=./wtr.db ./wtr list -c measures
        WTR_CACHE=./wtr.db ./wtr observe -l CULB -m WATHTE